### Matematik va Static usullarni qo'llash

statistics.png

In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5, 4)

In [3]:
arr

array([[ 0.79104994, -0.4776007 ,  0.14135461, -0.46644514],
       [ 1.56197501, -0.65737118,  1.3257657 ,  0.18363356],
       [-0.26636218,  1.35718006, -0.67112634,  1.2676614 ],
       [-0.77305469,  0.97732533,  0.81790183, -0.18902462],
       [-0.88796363,  1.38068841, -1.17554921,  0.87468719]])

### `sum` metodi

In [5]:
# arraydagi barcha malumotlar yig'indisi
arr.sum()

5.114725353587964

In [7]:
#yoki
np.sum(arr)

5.114725353587964

In [8]:
arr.sum(axis=1) #bu yerdagi (=1) arrni qatorlari(vertikal=x) yig'indisni beradi

array([-0.01164128,  2.41400309,  1.68735294,  0.83314784,  0.19186277])

In [26]:
arr.sum(axis=0) #(=0)esa ustunlari (gorizontal=y) yig'indisini beradi

array([0.42564445, 2.58022193, 0.4383466 , 1.67051238])

### `mean` metodi 
o'rtacha arifmetik qiymat

In [27]:
data = np.arange(5)

In [28]:
data

array([0, 1, 2, 3, 4])

In [29]:
a = np.sum(data)/len(data) #sonni o'rtacha qiymati
a

2.0

yuqoridagi usulni numpy da ishlatib ko'ramiz

In [30]:
np.mean(data)

2.0

In [31]:
#yoki
data.mean()

2.0

In [32]:
#arrayni mean metodida qo'llab ko'ramiz
arr

array([[ 0.79104994, -0.4776007 ,  0.14135461, -0.46644514],
       [ 1.56197501, -0.65737118,  1.3257657 ,  0.18363356],
       [-0.26636218,  1.35718006, -0.67112634,  1.2676614 ],
       [-0.77305469,  0.97732533,  0.81790183, -0.18902462],
       [-0.88796363,  1.38068841, -1.17554921,  0.87468719]])

In [33]:
np.mean(arr)#arr dagi barcha qiymatlarni o'rtacha qiymatini chiqaradi

0.2557362676793982

In [34]:
np.mean(arr, axis=1)#arr ni x o'qlarini o'rtacha qiymatini beradi

array([-0.00291032,  0.60350077,  0.42183823,  0.20828696,  0.04796569])

In [36]:
np.mean(arr, axis=0)# y oqini o'tacha qiymati

array([0.08512889, 0.51604439, 0.08766932, 0.33410248])

In [37]:
#yoki
arr.mean(axis=0)

array([0.08512889, 0.51604439, 0.08766932, 0.33410248])

### `cumsum` metodi
bu metodni ishlashi boshidagi 2ta sonni yig'indisini 2chi sonni o'rniga yozadi, keyin 3ta sonni yig'indisini 3chi sonni o'rniga yozadi vhk...

In [38]:
data

array([0, 1, 2, 3, 4])

In [39]:
data.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

In [40]:
#yoki
np.cumsum(data)

array([ 0,  1,  3,  6, 10], dtype=int32)