### `Sorting`
Arrayni Tartiblash

In [2]:
import numpy as np

In [4]:
#data 
arr = np.random.rand(4) #taxminiy sonlar yaratamiz
arr

array([0.59327352, 0.90622337, 0.55629386, 0.77716429])

`.sort` funksiyasi
bu funksiya arryni tartiblashga, eng kichik sondan tartiblaydi

In [8]:
# 1
arr.sort()
arr

array([0.55629386, 0.59327352, 0.77716429, 0.90622337])

In [10]:
# 2
sort_arr = np.sort(arr)
sort_arr

array([0.55629386, 0.59327352, 0.77716429, 0.90622337])

### Teskari tariblash
Teskari tartiblash da fuksiya yo'q shunichun boshqa usul qo'llaniladi

In [13]:
rev_arr = -np.sort(-arr) # teslari tartiblash
rev_arr

array([0.90622337, 0.77716429, 0.59327352, 0.55629386])

`2D arrayni tartiblash`

In [14]:
arr2d = np.random.randn(2, 4) # 2,4 shapeli array
arr2d

array([[ 0.35666536,  0.05067444,  0.60510309,  1.16171449],
       [-0.18499964,  1.34233442, -0.02708585, -0.07103611]])

In [15]:
row_srt = np.sort(arr2d, axis = 0) # ustunlarni ustma ust tartublash
row_srt

array([[-0.18499964,  0.05067444, -0.02708585, -0.07103611],
       [ 0.35666536,  1.34233442,  0.60510309,  1.16171449]])

In [17]:
row_srt = -np.sort(-arr2d, axis = 0) # ustunlarni ustma ust teskari tartublash
row_srt

array([[ 0.35666536,  1.34233442,  0.60510309,  1.16171449],
       [-0.18499964,  0.05067444, -0.02708585, -0.07103611]])

In [18]:
col_srt = np.sort(arr2d, axis = 1) # qatorlarni tartublash
col_srt

array([[ 0.05067444,  0.35666536,  0.60510309,  1.16171449],
       [-0.18499964, -0.07103611, -0.02708585,  1.34233442]])