### `Linear Algebra`

In [43]:
import numpy as np

In [44]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[7., 8., 9.], [10., 11., 12.]])

In [45]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
y

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [47]:
x+y #arraylarni qo`shish

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [48]:
x*y #ko`paytirish

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [49]:
x*5 # x ning harbir elementini 5 ga ko`paytirish

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [50]:
#shape(2,3)li arrayni shape(3,2)li arrayga qo`shish
x2 = np.array([[7., 8., 7.],[9., 10., 1.]])
y2 = np.array([[1, 2],[3, 4],[5, 6]]) # shape(3,2)li array yaratamiz

In [55]:
np.dot(x2,y2) #x*y

array([[66., 88.],
       [44., 64.]])

In [56]:
x2.dot(y2) #x*y

array([[66., 88.],
       [44., 64.]])

In [58]:
np.dot(y2,x2) #y*x

array([[ 25.,  28.,   9.],
       [ 57.,  64.,  25.],
       [ 89., 100.,  41.]])

In [59]:
#Linear Algebrea
from numpy.linalg import inv

`for more` https://towardsdatascience.com/introduction-to-linear-algebra-with-numpy-79adeb7bc060