# Mantiqiy shart operatorlarini  Massiv operatori sifatida qo'llash

In [1]:
import numpy as np

Ikkita array yaratib (x_arr, y_arr), agar `True` ni qaytarsa x_arrdan olgan, aksincha `False` ni qaytarsa y_arrdan olgan bo'ladi

In [2]:
# array yaratamiz
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

endi shartni `condition`ni yaratib olamiz, va arraylarmizga mos ravishda shartlarni beramiz

In [12]:
cond = np.array([True, False, True, True, False])# cond==Tru->x_arr, cond==False->y_arr

`where`

In [13]:
result = np.where(cond, x_arr, y_arr) # .where('shart', 'true', 'false')
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

Boshqa misol

In [20]:
# (3, 3) o'lchamli array
arr = np.random.randn(3, 3)
arr

array([[-0.43604083,  0.22014598, -0.32923829],
       [-0.76021655, -1.11481099, -0.46262977],
       [ 2.27971533,  2.91452715,  0.92247675]])

In [21]:
result2 = np.where(arr < 0, -2, 2) # arr<0 bo'lsa (-2)ga, aksholda (2)ga teng qilsin
result2

array([[-2,  2, -2],
       [-2, -2, -2],
       [ 2,  2,  2]])