# Arifmetik ammallar 

In [1]:
import numpy as np

In [6]:
# 2ta array yaratib olamiz
arr1 = np.arange(3,9).reshape(2, 3)
arr2 = np.arange(9,15).reshape(2, 3)

In [7]:
arr1

array([[3, 4, 5],
       [6, 7, 8]])

In [8]:
arr2

array([[ 9, 10, 11],
       [12, 13, 14]])

In [9]:
# ko'pyatirish
arr1 * arr2 # ikkita arrayni bir biriga ko'paytirish

array([[ 27,  40,  55],
       [ 72,  91, 112]])

In [10]:
# bo'lish
arr1 / arr2 # arrayni bir biriga bo'lish

array([[0.33333333, 0.4       , 0.45454545],
       [0.5       , 0.53846154, 0.57142857]])

In [11]:
# qo'shish
arr1 + arr2 # arratlarni qo'shish

array([[12, 14, 16],
       [18, 20, 22]])

In [12]:
# ayirish
arr1 + arr2 # arraylarni ayirish

array([[12, 14, 16],
       [18, 20, 22]])

In [14]:
# kvadratga oshirish (square)
arr1 ** 2 # arr1 ning 2darajasi

array([[ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [15]:
# ildizdan chiqarish (sqrt)
arr2 ** 0.5 #arr2 ning ildizi

array([[3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739]])